- id: grey
  name: grey
  description: "grey: The uncompromising Python code formatter"
  entry: grey
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
- id: grey-jupyter
  name: grey-jupyter
  description:
    "grey: The uncompromising Python code formatter (with Jupyter Notebook support)"
  entry: grey
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi, jupyter]
  additional_dependencies: [".[jupyter]"]
